version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - crm
    restart: unless-stopped

  crm-service:
    container_name: crm-service
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
      - MAIL_USERNAME=crm@gmail.com
      - MAIL_PASSWORD=password
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - postgres
    networks:
      - crm

  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - crm

  grafana:
    image: "grafana/grafana"
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - crm

networks:
  crm:
    name: crm-network

volumes:
  postgres:
