api:
  info:
    title: Wealth Management API Services
    description: API to fetch review details for application
    version: 1.0.0
    terms-of-service: https://beetsoft.com.vn/terms/
    contact:
      name: BEETSOFT CO., LTD
      email: contact@beetsoft.com.vn
      url: https://beetsoft.com.vn/
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html

server:
  port: 8080
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'






#AWS properties
cloud:
  aws:
    region:
      static: ap-southeast-1
    stack:
      auto: false
    credentials:
      accessKey: AKIAWAU5ALQEYVCFI54L
      secretKey: 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
      bucketName: weath-management

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
